substitutions:
  device: esp_pixel_clock_en
  name: pixel-clock-en
  friendly_name: ESPHome Pixel Clock
  project_name: "ajs.Pixel_Clock"
  project_version: "1.1.5"
  update_interval: 60s
  comment: "Ulanzi Pixel Clock | EHMTXv2"
  weekdays: "SUMOTUWETHFRSA"
  date_to: ""

dashboard_import:
  package_import_url: github://andrewjswan/pixel-clock/pixel-clock.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/pixel-clock
    files:
      - packages/common.yaml
      - packages/framework-arduino.yaml
      - packages/pixel_clock.yaml
      - packages/pixel_clock_aab_light.yaml
      # - packages/pixel_clock_aab_tiny.yaml
      # - packages/pixel_clock_sun.yaml
      # - packages/pixel_clock_timezone.yaml
    refresh: 1s

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: ${name}
  birth_message:
    topic: ${name}/status
    payload: online
  will_message:
    topic: ${name}/status
    payload: offline
