esphome:
  name: tc001-display
  friendly_name: "TC001 Display"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "TC001-Fallback"
    password: !secret ap_password

captive_portal:

# MQTT Configuration for HiveMQ
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: tc001_display
  discovery: false

# Text sensor for receiving pixel commands
text_sensor:
  - platform: mqtt_subscribe
    name: "Pixel Command"
    id: pixel_command
    topic: "tc001/command"
    on_value:
      then:
        - logger.log:
            format: "Received command: %s"
            args: ['x.c_str()']
